### ISSUE TITLE
Images on my portfolio not showing 

### ISSUE THREAD

**Issue by aliforgetti** [dragonman225/notablog#13]
![image](https://user-images.githubusercontent.com/17579534/95802507-3f97c880-0cc3-11eb-8267-1c9e544084eb.png)
This is what they look like. I have been trying to fix this. Tried updating notablog but did not work. Using notablog starter

**Comment by dragonman225** [comment]
Umm, that's odd, since images on my blog are working.

Does the URLs of those images on your portfolio look like below?

<p><strong>https://www.notion.so/signed/</strong>https%3A%2F%2Fs3-us-west-2.amazonaws.com%2Fsecure.notion-static.com%2Fc5a88411-c761-4386-8283-0bb41dc70361%2Fimage01.png<strong>?table=block&id=25c812d9-12ef-412d-9e7e-c9b809b5b252</strong></p>

Check especially if the bold parts exist.

**Comment by aliforgetti** [comment]
**https://www.notion.so/signed/**https%3A%2F%2Fs3-us-west-2.amazonaws.com%2Fsecure.notion-static.com%2Fa7f7a502-36ef-41b1-bc17-58b4cb6c6ba3%2FUntitled.png?width=1123

It has the first part but not the send part that you bolded.

**Comment by diegoalbuquerque** [comment]
I have the same problem. Is difficult to download the entire image and change the img links to a relative folder ? This will separate entire site from notion, i think.

**Comment by aliforgetti** [comment]
@diegoalbuquerque any ideas on how to fix this?

**Comment by Vshalson** [comment]
I experienced this issue today. And found page was accidentally not shared to web.
Solution worked for me:
**Allow "Share to web", commit changes and git push.**

**Comment by dragonman225** [comment]
> I experienced this issue today. And found page was accidentally not shared to web.
> Solution worked for me:
> **Allow "Share to web", commit changes and git push.**

Since images, videos, files, ... are served from Notion's server.
And that's why notablog requires users to enable "Share to web" on their tables, so that anonymous readers of a site can access the resources.
