### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading '0') at getAllBlocksInOnePage

### ISSUE THREAD

**Issue by ArtyomCZ** [dragonman225/notablog#41]
Hi, when I try to generate, this error appears. I don't know if I'm just doing something wrong or if it's a bug.

![image](https://user-images.githubusercontent.com/16862369/176325624-d4bc59c2-bc68-4838-a71e-e3c7b95ace36.png)

**Comment by aptrinh** [comment]
I'm having the same exact error as well. @ArtyomCZ what have you changed before generating? I only added a post to Notion and updated Notablog from 0.7.0 to 0.8.0

**Comment by tatung** [comment]
I have the same problem since today. Yesterday was fine (using 0.8.0). Look like 0.8.0 was updated a week ago, so I think it is not the new version problem. I ran some quick debug and found this:

```
I/notablog(20220629T130455.627): Fetch site metadata
/Users/tatung/.nvm/versions/node/v18.4.0/lib/node_modules/notablog/node_modules/nast-util-from-notionapi/dist/index.js:1049
    const record = response.results[0];
                                   ^

TypeError: Cannot read property '0' of undefined
    at getAllBlocksInOnePage (/Users/tatung/.nvm/versions/node/v18.4.0/lib/node_modules/notablog/node_modules/nast-util-from-notionapi/dist/index.js:1049:36)
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
    at async Object.getOnePageAsTree (/Users/tatung/.nvm/versions/node/v18.4.0/lib/node_modules/notablog/node_modules/nast-util-from-notionapi/dist/index.js:1039:23)
    at async parseTable (/Users/tatung/.nvm/versions/node/v18.4.0/lib/node_modules/notablog/dist/index.js:421:29)
    at async generate (/Users/tatung/.nvm/versions/node/v18.4.0/lib/node_modules/notablog/dist/index.js:900:25)
```

The `results` in `response` is empty with `message: 'Something went wrong'`
<img width="473" alt="Screen Shot 2022-06-29 at 14 15 37" src="https://user-images.githubusercontent.com/1425229/176357387-e18868fa-ce2d-4cc3-b4e0-0068abe2f7ff.png">

**Comment by ArtyomCZ** [comment]
> I'm having the same exact error as well. @ArtyomCZ what have you changed before generating? I only added a post to Notion and updated Notablog from 0.6.3 to 0.8.0
> 
> ![image](https://user-images.githubusercontent.com/65725739/176342397-8a9fab57-ab72-47eb-a30b-c4e1c9cf6a0d.png)

Nothing, I just added a new post and wanted to regenerate.

**Comment by aptrinh** [comment]
The issue stopped happening for me as of the time of this reply.

**Comment by dragonman225** [comment]
It's also generating normally at the time of this reply.

From @tatung's inspection, I think there was an incident on Notion's server, since a `response` object with only the `message` property isn't a valid [Notion error response](https://notionapi.netlify.app/interfaces/errorresponse.html) as far as I know, and no code in Notablog or its dependencies would set the response to that.

> The `results` in `response` is empty with `message: 'Something went wrong'` <img alt="Screen Shot 2022-06-29 at 14 15 37" width="473" src="https://user-images.githubusercontent.com/1425229/176357387-e18868fa-ce2d-4cc3-b4e0-0068abe2f7ff.png">

**Comment by charlesyiu** [comment]
I recently setup a GitHub action to generate a notion site. It had no errors when ran with the configuration provided in the starter repository. I then made it commit the changes to its own repository when the error appeared.
workflow: [charlesyiu/notion](https://github.com/charlesyiu/notion/blob/master/.github/workflows/nodejs.yml)
error:
<img width="970" alt="Screenshot 2022-11-24 at 1 32 52 AM" src="https://user-images.githubusercontent.com/90403890/203612158-33efc70a-61bd-4ed0-a883-bf56784acf83.png">
