### ISSUE TITLE
Code highlight and page width problem

### ISSUE THREAD

**Issue by hhmy27** [dragonman225/notablog#48]
Hi, I very appreciate for your work
I have been use notablog to build my blog, but I meet two problem
**code highlight**
seems like notablog do not support `shell` and `go` code highlight？
the next two image is notion code block:
<img width="366" alt="image" src="https://user-images.githubusercontent.com/31946303/202893995-6fbb9769-94c4-4c15-9bfd-207c8eb3f5e7.png">

<img width="343" alt="image" src="https://user-images.githubusercontent.com/31946303/202894052-fa5946db-6417-46cf-9c47-259f14513178.png">

the next two image is notablog effect, seems like the code highlight doesn't work? :
<img width="526" alt="image" src="https://user-images.githubusercontent.com/31946303/202894073-f533c192-0605-47be-8a87-c1c9c4d40952.png">

<img width="438" alt="image" src="https://user-images.githubusercontent.com/31946303/202894087-a8d2b1c7-b781-4b55-82bc-d90a62d24237.png">

I have been check this issue https://github.com/dragonman225/notablog/issues/25, but I don't know how to fix it.
Please spare a moment to support it if you can, thanks a lot.

**page width**
the page rendering works great, but I want to make the page wider, how to set it?

like this code block, the block is too short to show all annotation, I want to make this code block wider, it will make reader feel more  comfortable.
<img width="1109" alt="image" src="https://user-images.githubusercontent.com/31946303/202894312-1b890a91-73b1-4169-a2cf-b6f5b2cce01e.png">

---
Thank you for your work again

**Comment by dragonman225** [comment]
Hi @hhmy27, thanks for your feedback!

### About "code highlight"

Notablog uses PrismJS, in theory, it *can* support hundreds of languages [listed here](https://prismjs.com/#supported-languages). The problem, however, is that we lack the complete *mapping* of language names. For example, C++ is called `C++` in Notion, but `cpp` in PrismJS, we need to map `C++` to `cpp` so that PrismJS knows which language it is highlighting. The mapping code is [here](https://github.com/dragonman225/nast/blob/f8188c7ec5aad9fe9fe80f9b354d6e44c6f3fdd1/packages/nast-util-to-react/src/util-prismjs.ts#L164), the keys of the `map` object are names in Notion, and the values of the object are names in PrismJS. The mapping is incomplete, if you would like to add support for Go and Shell, you can find out their mappings and add them into the `map` object. It's best to sort the mappings alphabetically, so it's easier for others to see what are supported and what are not in the future.

Btw, you can select `Bash` for your shell script, it's already supported!

### About "page width"

Anything about styling or layout can be tuned with CSS, if you want to change the page width, find [this file](https://github.com/dragonman225/notablog-starter/blob/2d8c6265184a8de3de9297295098440ba45369e7/themes/pure-ejs/assets/css/notablog.css#L76) in your own `notablog-starter` and change it. Note that the default theme uses the same page width for `ArticleList` (homepage's list, tag page's list), and `Header` (an article's title and icon) if you just want to change an article's page width, move the `PageRoot` CSS class out to its own rule. Don't forget to check if your changes also look good on mobile, edit CSS rules that are inside `@media ...` blocks if necessary.

Tip: You can leverage Chrome or Firefox's devtools to explore your ideal values first

https://user-images.githubusercontent.com/25148955/202909571-87a47c6b-2516-4c02-bf00-7564b88b0b91.mp4

**Comment by hhmy27** [comment]
Thanks for your kind reply, it's very helpful!
I adjusted the page width as you suggested. Regarding language support, I have applied for an MR https://github.com/dragonman225/nast/pull/13,  It will be great if you have time to check : )
