### ISSUE TITLE
How to Set A Default Page or Route

### ISSUE THREAD

**Issue by vwxyzjn** [dragonman225/notablog#6]
Hi, the default page now looks like the following

![image](https://user-images.githubusercontent.com/5555347/77783984-29c8fb80-7030-11ea-9a1d-c0a83293cf26.png)

Is there any way to set the default page to something like "About"? In general, is there anywhere we can customize the "Home" page?

Thanks a lot.

**Comment by dragonman225** [comment]
Hi,

In Notablog's design, the "Home" page is a "derived" page, which is generated from the metadata of the "real" pages one creates on Notion. So, there's no "default page" concept here.

As for customizing the "Home" page, you can edit the [template](https://github.com/dragonman225/notablog-starter/blob/master/themes/pure/layout/index.html). But before you start, I would like to inform that theming is a highly unstable feature, since the template engine may change, the API may also change, and the [documentation](https://github.com/dragonman225/notablog#api-reference-outdated) is not up to date. However, it can be done. For example, one of my friend successfully customized his "Home" page: [website](https://maximusology.netlify.com/index.html), [source code](https://github.com/ycEw18913/Portfolio/blob/master/themes/pure/layout/index.html).

**Comment by vwxyzjn** [comment]
Fixed by the referenced commit above. Thanks for the support.

**Comment by sabiou** [comment]
So there is no way to set up a default page without doing theming stuff ?

If that's the case I think it's just not a good idea, I actually just want to upload my personal "about me" one page and have it as default.

**Comment by bgmort** [comment]
I came here to request the same thing. It would be nice to be able to designate a page from the table as the index page rather than customizing the index template.
